In [3]:
import numpy as np

In [108]:
def gauss(mat):
    mod_det=1
    l = len(mat)
    for col in range(l-1):
        if mat[col][col]==0:
            for cand in range(col+1, l):
                if mat[cand][col]!=0:
                    row_temp = mat[cand].copy()
                    mat[cand]=mat[col].copy()
                    mat[col]=row_temp.copy()
                    mod_det*=-1
                    print(mod_det)
                    break
                if cand==l-1:
                    return f'Nie można przez zera w kolumnie {col}'
        for row in range(col+1,l):
            factor = mat[row][col]/mat[col][col]
            for el in range(col, l):
                mat[row][el] = mat[row][el] - (factor*mat[col][el])
    det=1
    for i in range(l):
        det*=mat[i][i]
    return round(det*mod_det)

In [128]:
x = np.array([[np.random.randint(-10,10) for y in range(9)] for z in range(9)])
print(x)
gauss(x)

[[ -1  -8  -7   0  -5   3   1   0   2]
 [  6   6  -2   9   3  -7   3   4  -7]
 [ -9  -7  -5   3  -5   6  -3 -10   2]
 [ -6   5   9  -5   0  -5  -5  -8   9]
 [ -8  -4  -3   9   9  -5   9  -5   6]
 [ -1   4  -4   6   4  -4   0   2   4]
 [ -7  -7  -9   1   7   8  -3   0 -10]
 [  8   1   9  -9   4  -4   7  -2  -2]
 [ -2  -9   5  -4   8  -8  -1   5   3]]
-1


495331200