In [7]:
import numpy as np

In [45]:
def gauss(mat):
    mod_det=1
    l = len(mat)
    for col in range(l-1):
        if mat[col][col]==0:
            for cand in range(col+1, l):
                if mat[cand][col]!=0:
                    row_temp = mat[cand].copy()
                    mat[cand]=mat[col].copy()
                    mat[col]=row_temp.copy()
                    mod_det*=-1
                    break
                if cand==l-1:
                    return f'Nie można przez zera w kolumnie {col}'
        for row in range(col+1,l):
            factor = mat[row][col]/mat[col][col]
            for el in range(col, l):
                mat[row][el] = mat[row][el] - (factor*mat[col][el])
    det=1
    for i in range(l):
        det*=mat[i][i]
    return round(det*mod_det)

In [58]:
x = np.array([[np.random.randint(-10,10) for y in range(5)] for z in range(5)])
print(x)
gauss(x)

[[  9   9 -10   6   9]
 [ -4   5  -1 -10   0]
 [  9  -4  -8  -8  -2]
 [ -3   9   0   0  -3]
 [  3   2   8  -5   4]]


166455

In [370]:
def mgj_rev(mat):
    l = len(mat)
    res = np.eye(l)
    for col in range(l-1):
        if mat[col][col]==0:
            for cand in range(col+1, l):
                if mat[cand][col]!=0:
                    row_temp = mat[cand].copy()
                    mat[cand]=mat[col].copy()
                    mat[col]=row_temp.copy()
                    row_temp = res[cand].copy()
                    res[cand]=res[col].copy()
                    res[col]=row_temp.copy()
                    break
                if cand==l-1:
                    return f'Nie można przez zera w kolumnie', f'{col}'
        for row in range(col+1,l):
            factor = mat[row][col]/mat[col][col]
            for el in range(col, l):
                mat[row][el] = mat[row][el] - (factor*mat[col][el])
            for el in range(l):
                res[row][el] = res[row][el] - (factor*res[col][el])
    for one in range(l):
        if mat[one][one]==0:
            print (f'Macierz nieodwracalna')
            return f'macierz', f'nieodwracalna'
    for col in range(1, l):
        for row in range(col):
            factor = mat[row][col]/mat[col][col]
            for el in range(col, l):
                mat[row][el] = mat[row][el] - (factor*mat[col][el])
            for el in range(l):
                res[row][el] = res[row][el] - (factor*res[col][el])
    for one in range(l):
        if mat[one][one]!=1:
            skalar = mat[one][one]
            for el in range(l):
                res[one][el] = res[one][el]/skalar
                mat[one][el] = mat[one][el]/skalar
    return mat, res

In [406]:
x = np.array([[np.random.randint(-10,10) for y in range(3)] for z in range(3)])
xx = np.array([[1,1,2],[2,3,4],[2,1,5]])
print(x)
y, z = mgj_rev(x)
print(f'mat: {y}\n rev: {z}')

[[ -3   0  -6]
 [ -2   2   8]
 [  4  -8 -10]]
mat: [[1 0 0]
 [0 1 0]
 [0 0 1]]
 rev: [[-0.24444444 -0.26666667 -0.06666667]
 [-0.06666667 -0.3        -0.2       ]
 [-0.04444444  0.13333333  0.03333333]]
