In [93]:
import math
import numpy as np

In [94]:
def Sar(mat):
    if len(mat)==1:
        return mat[0][0]
    if len(mat)!=len(mat[0]):
        return f'Zle wymiary'
    mat_n=len(mat)
    if mat_n>=3:
        for i in range(len(mat)-1):
            to_add = []
            for j in range(mat_n):
                to_add.append(mat[j][i])
            mat = np.c_[mat, to_add]
    res = 0
    if len(mat)==2:
        res+=mat[0][0]*mat[1][1]
        res-=mat[1][0]*mat[0][1]
        return res
    for i in range(mat_n):
        res_add = 1
        for j in range(mat_n):
            res_add*=mat[j][j+i]
        res+=res_add
    for i in range(mat_n):
        res_ded = 1
        for j in range(mat_n):
            res_ded*=mat[j][mat_n-1-j+i]
        res-=res_ded
    return res


In [95]:
def multi(t1,t2):
    r=[]
    for i in range(len(t1)):
        temp=[]
        for j in range(len(t2[0])):
            temp2=0
            for k in range(len(t1[0])):
                to_temp2=t1[i][k]*t2[k][j]
                to_temp2_round = np.round(to_temp2, 4)
                temp2+=to_temp2_round
            temp.append(np.round(temp2,2))
        r.append(temp)
    return r

In [96]:
def multi_skalar(t1, t2=1):
    r=[]
    for i in range(len(t1)):
        r_t=[]
        for j in range(len(t1[0])):
            r_t_t = t1[i][j]*(t2)
            r_t.append(np.round(r_t_t,4))
        r.append(r_t)
    return r

In [97]:
def Short(mat, i, j):
    mat_S=[]
    for i_i in range(len(mat)):
        if i_i!=i:
            mat_S.append(list(mat[i_i].copy()))
    for j_i in range(len(mat_S)):
        mat_S[j_i].pop(j)
    return Sar(np.array(mat_S.copy()))

In [98]:
def M(mat):
    mat_M=[]
    for i in range(len(mat)):
        mat_M_i=[]
        for j in range(len(mat)):
            minus=1
            if (i+j)%2==1:
                minus=-1
            mat_M_i.append(minus*Short(mat,i,j))
        mat_M.append(mat_M_i)
    return mat_M

In [99]:
def Lapl(mat):
    L_M = M(mat)
    res_L = 0
    for i in range(len(mat[1])):
        res_L+=mat[1][i]*L_M[1][i]
    return res_L

In [100]:
def Rev(mat):
    R_M=M(mat)
    print(f'M: {np.array(R_M)}')
    mat_Rev=np.array(R_M).T
    print(f'M_T: {mat_Rev}')
    if len(mat)<=3:
        det = Sar(mat.copy())
    if len(mat)>3:
        det = Lapl(mat)
    print(f'det: {det}')
    if det==0:
        return "Macierz jest osobliwa i nie ma odwrotności"
    mat_Rev=multi_skalar(mat_Rev, 1/det)
    return mat_Rev

In [101]:
x=[[2,5,7],[6,3,4],[5,-2,-3]]
y=[[1,-1,2,4],[0,1,0,3],[5,7,-2,0],[2,0,-1,4]]
z=[[1,2,-1],[1,1,-1],[2,1,0]]
z1=[[-2,3],[-4,7]]
#Rev(z)
#x =multi(z, Rev(z))
#x
# xx = np.linalg.inv(y)
# x = np.dot(y, np.linalg.inv(y))
# x
_x= Rev(x)
print(np.array(_x))
print(np.array(multi(x,_x)))


M: [[ -1  38 -27]
 [  1 -41  29]
 [ -1  34 -24]]
M_T: [[ -1   1  -1]
 [ 38 -41  34]
 [-27  29 -24]]
det: -1
[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [102]:
x=[0,0,0]